#!/usr/bin/env php
<?php

use Linker\Installer\Installer;

$installer = new Installer();

if(!$installer->init(__DIR__,$argv ?? [],"v1.0"))
    Installer::echo("Linker installer failed to execute command! Try again!\n",33);
