#!/usr/bin/env php
<?php
$dir = __DIR__;

require_once(__DIR__."/../../autoload.php"); 


use Linker\Installer\Installer;

$installer = new Installer();

if(!$installer->init($dir,$argv ?? [],"v1.41"))
    Installer::echo("Linker installer failed to execute command! Try again!\n",33);
